# Generated by Django 4.1.3 on 2022-12-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_numero_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=40)),
                ('categoria_importancia', models.IntegerField()),
                ('categoria_descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_nombre', models.CharField(max_length=40)),
                ('post_totalcaracteres', models.IntegerField()),
                ('post_puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=40)),
                ('usuario_apellido', models.CharField(max_length=40)),
                ('usuario_mail', models.CharField(max_length=40)),
            ],
        ),
    ]
